# Generated by Django 4.1.2 on 2022-10-15 13:45

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='ingredients',
            field=wagtail.fields.StreamField([('ingredients', wagtail.blocks.StructBlock([]))], blank=True, use_json_field=True),
        ),
    ]
