# Generated by Django 4.1.2 on 2022-10-15 14:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipepage_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='ingredients',
            field=wagtail.fields.StreamField([('ingredients', wagtail.blocks.StructBlock([('unit', wagtail.blocks.ChoiceBlock(choices=[('el', 'Esslöffel'), ('tl', 'Teelöffel')], label='Einheit', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
