# Generated by Django 4.1.2 on 2022-10-15 14:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipepage_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepage',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipepage',
            name='sections',
            field=wagtail.fields.StreamField([('sections', wagtail.blocks.StructBlock([]))], default='', use_json_field=False),
            preserve_default=False,
        ),
    ]
