# Generated by Django 4.1.2 on 2022-10-15 14:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipepage_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='sections',
            field=wagtail.fields.StreamField([('sections', wagtail.blocks.StreamBlock([('ingredients', wagtail.blocks.StreamBlock([('name', wagtail.blocks.TextBlock(help_text='Zutat', required=True)), ('amount', wagtail.blocks.FloatBlock(help_text='Menge', label='Menge', max_value=999999.0, min_value=0.0, required=False)), ('unit', wagtail.blocks.ChoiceBlock(choices=[('el', 'Esslöffel'), ('tl', 'Teelöffel')], label='Einheit', required=False))], blank=True, use_json_field=False))]))], use_json_field=False),
        ),
    ]
