# Generated by Django 4.1.2 on 2022-10-16 09:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipepage_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='sections',
            field=wagtail.fields.StreamField([('sections', wagtail.blocks.StructBlock([('instructions', wagtail.blocks.RichTextBlock(label='Anweisungen', required=True))]))], use_json_field=False),
        ),
    ]
