# Generated by Django 4.1.2 on 2022-10-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipepage_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='portions',
            field=models.PositiveSmallIntegerField(default=4),
            preserve_default=False,
        ),
    ]
