# Generated by Django 4.1.2 on 2022-10-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_recipepage_portions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='portions',
            field=models.PositiveSmallIntegerField(verbose_name='Portionen'),
        ),
    ]
