# Generated by Django 4.1.2 on 2022-10-16 12:38

from django.db import migrations
import recipes.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_recipepage_portions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='comments',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='sections',
            field=wagtail.fields.StreamField([('sections', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Überschrift', required=False)), ('ingredients', wagtail.blocks.ListBlock(recipes.models.IngredientBlock, icon='form', label='Zutaten', required=True)), ('instructions', wagtail.blocks.RichTextBlock(label='Anweisungen', required=True))]))], use_json_field=False, verbose_name='Rezeptabschnitte'),
        ),
    ]
