# Generated by Django 4.1.2 on 2022-10-25 09:33

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_alter_recipepage_comments_alter_recipepage_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='comments',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Kommentar'),
        ),
    ]
