# Generated by Django 4.1.2 on 2022-10-25 10:41

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_alter_recipepage_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='source',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Quelle'),
        ),
    ]
